In [5]:
import pandas as pd

df = pd.read_csv('../data/raw.csv')
df.head(1000)

           date      time                                              tweet
0    2023-01-01       NaN  Resuelto, much√≠simas gracias , excelente servi...
1    2023-01-02       NaN                       Muchas gracias, espero su dm
2    2023-01-02       NaN                                    Muchas gracias!
3    2023-01-02       NaN  Algo similar me paso. Quer√≠a renovar mi token ...
4    2023-01-02       NaN  Yeeeei! a trav√©s de mi cuenta en acabo de cont...
..          ...       ...                                                ...
807  2024-04-21  15:21:43                   Ahora confirmo, gracias estimado
808  2024-04-23  22:52:05                     üòî de acuerdo!! Muchas gracias.
809  2024-04-23  21:30:12  T√≠o cuando me van a graduar, tengo la TDC gara...
810  2024-04-25  00:51:24  una duda, con qui√©n tengo que ver si tengo pro...
811  2024-04-26  13:30:56  Wey, lo mejor de es que puedo pagar con Apple ...

[812 rows x 3 columns]

In [7]:
# Obtener fecha de inicio y fin
df['date'] = pd.to_datetime(df['date'])
df['date'].min(), df['date'].max()

(Timestamp('2023-01-01 00:00:00'), Timestamp('2024-04-26 00:00:00'))

In [9]:
# Obtener a partir de que "date" hay "time" != NaN
df_notna = df[df['time'].notna()]
df_notna['date'].min()

Timestamp('2023-06-12 00:00:00')

In [14]:
# Dataframe con "tweet"'s repetidos
df_repeated = df[df.duplicated(subset=['tweet'], keep=False)]

# Mostrar valores repetidos
df_repeated.sort_values(by='tweet')

,date,time,tweet
360,2023-05-29,NaT,Con Hey siempre tienes el control de tus finan...
387,2023-06-10,NaT,Con Hey siempre tienes el control de tus finan...
363,2023-05-30,NaT,Con Hey siempre tienes el control de tus finan...
96,2023-01-28,NaT,Excelente
222,2023-03-13,NaT,Excelente
...,...,...,...
578,2023-10-21,2024-05-04 03:46:33,¬°Te vamos a sorprender! ‚≠êÔ∏è Para todos nuestros...
625,2023-10-31,2024-05-04 14:25:33,¬øEres un estudiante y tienes una idea brillant...
613,2023-10-30,2024-05-04 23:34:34,¬øEres un estudiante y tienes una idea brillant...
675,2023-12-01,2024-05-04 21:23:51,üéÅ ¬°Promoci√≥n para todos nuestros clientes Hey!...
714,2024-01-10,2024-05-04 12:36:49,üéÅ ¬°Promoci√≥n para todos nuestros clientes Hey!...

In [15]:
# Cargar datos de "data/processed.csv"
df_processed = pd.read_csv('../data/processed.csv')

# Mostrar head
df_processed.head(1000)

,date,time,tweet,category,tone
0,2023-01-01,NaN,"Resuelto, much√≠simas gracias , excelente servi...",Agradecimiento,Amigable
1,2023-01-02,NaN,"Muchas gracias, espero su dm",Agradecimiento,Formal
2,2023-01-02,NaN,Muchas gracias!,Agradecimiento,Amigable
3,2023-01-02,NaN,Algo similar me paso. Quer√≠a renovar mi token ...,Quejas,Enojado
4,2023-01-02,NaN,Yeeeei! a trav√©s de mi cuenta en acabo de cont...,Agradecimiento,Emocionado
...,...,...,...,...,...
807,2024-04-21,15:21:43,"Ahora confirmo, gracias estimado",Agradecimiento,Formal
808,2024-04-23,22:52:05,üòî de acuerdo!! Muchas gracias.,Agradecimiento,Amigable
809,2024-04-23,21:30:12,"T√≠o cuando me van a graduar, tengo la TDC gara...",Pedir ayuda,Preocupado
810,2024-04-25,00:51:24,"una duda, con qui√©n tengo que ver si tengo pro...",Pedir ayuda,Serio
811,2024-04-26,13:30:56,"Wey, lo mejor de es que puedo pagar con Apple ...",Experiencias de usuario,Amigable